version: "3"
networks:
  default:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis-urlsho
    environment:
      - REDIS_PASSWORD=test

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=urls
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    container_name: mysql-urlsho
      
  consul:
    image: consul:latest
    container_name: consul-urlsho