version: "3"
networks:
  default:
    external:
      name: my-network

services:
  service.urlsho:
    build:
      context: . 
      dockerfile: Dockerfile
    image: urlsho
    container_name: service-urlsho
    environment:
      - REDIS_URI=redis://root:@redis:6379/0
      - MYSQL_URI=test:test@tcp(mysql:3306)/urls
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul

  microapi:
    image: microhq/micro
    container_name: microapi-urlsho
    command: api --handler=rpc
    ports:
      - "8080:8080"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=my.service
  