version: "2"

services:
  consul:
    image: consul:latest
    container_name: consul-urlsho
    command: consul agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"

  service.urlsho:
    image: golang:alpine
    container_name: urlsho
    volumes:
      - .:/go/src/url-shortener
    working_dir: /go/src/url-shortener
    build: ./url-shortener
    command: ./url-shortener --REDIS_URL='0.0.0.0:6379' --MYSQL_URL='root@/urls'
    ports:
      - "8080:8080"
    links:
      - redis
      - consul
      - mysql

  redis:
    image: redis:alpine
    container_name: redis-urlsho
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=urls
    container_name: mysql-urlsho
    ports:
      - "3306:3306"

  microweb:
    image: microhq/micro
    container_name: microweb-urlsho
    command: --registry=mdns web --address=0.0.0.0:8082
    ports:
      - "8082:8082"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=gomicro.api
    links:
      - consul
      - service.urlsho

  