version: "3"
networks:
  default:
    driver: bridge

services:
  service.urlsho:
    build:
      context: . 
      dockerfile: Dockerfile
    image: urlsho
    container_name: service-urlsho
    environment:
      - REDIS_URI=redis://:test@redis:6379/0
      - MYSQL_URI=test:test@tcp(mysql:3306)/urls
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul

  web.urlsho:
    build:
      context: ./url-shortener-web-client
      dockerfile: Dockerfile
    image: web-urlsho
    container_name: web-urlsho
    environment:
      - API_URL=http://microapi:8080
    ports:
      - "3000:3000"
  
  microapi:
    image: microhq/micro
    container_name: microapi-urlsho
    command: api --handler=rpc
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=my.service
    ports:
      - "8080:8080"
  